name: Github Actions Input Demo

on:
  workflow_call:
   inputs:
    username:
      required: true
      type: string
      default: 'Annie'



jobs:
  Demo:
    name: 'Testing Greeting Users'
    runs-on: self-hosted

    steps:
    - name: Greet User
      shell: pwsh
      run: |
        write-host "My Name is:  ${{ inputs.username }}"
