name: Github Actions Input Demo

on:
  workflow_call:
   inputs:
    Kind:
        required: true
        type: string
    ResourceName:
        type: string
    ResourceGroupName:
        type: string
    BicepFile:
       type: string
    ParamFile:
        type: string
    DeployInfrastructure:
        type: boolean


jobs:
  release:
    name: '${{ inputs.Kind }} Release'
    runs-on: self-hosted

    steps:
    - name: FunctionApp_Testing
      if: ${{ inputs.Kind }} == FunctionApp 
      uses: actions/functionapp@v0.0.6
      with:
        ResourceName: ${{inputs.ResourceName}}
        ResourceGroupName: ${{inputs.ResourceGroupName}}
        DeployInfrastructure: ${{inputs.DeployInfrastructure}}