name: Github Actions Input Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  workflow_call:
     inputs:
      username:
        description: 'UserName you want echo out...'
        required: true
        type: string
        default: DeanDefault

jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
        shell: bash