name: Github Actions Input Demo

on:
  workflow_call:
   inputs:
    Kind:
        description: ''
        required: true
        type: string
    ResourceName:
        description: ''
        type: string
    ResourceGroupName:
        description: ''
        type: string
    BicepFile:
       description: ''
       type: string
    ParamFile:
        description: ''
        type: string
    DeployInfrastructure:
        description: ''
        type: boolean


jobs:
  release:
    name: '${{ inputs.Kind }} Release'
    runs-on: self-hosted

    steps:
    - name: Greet User
      shell: pwsh
      run: |
        write-host "Kind:  ${{ inputs.Kind }}"
        write-host "ResourceName:  ${{ inputs.ResourceName }}"
        write-host "ResourceGroupName:  ${{ inputs.ResourceGroupName }}"